/*
 * Copyright 2013 Modeliosoft
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */  
                                    

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.01.10 at 01:18:11 PM CET
//
package org.modelio.audit.preferences.persistence.old;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>
 * Java class for ActivationStatus.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="ActivationStatus">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="enabled"/>
 * &lt;enumeration value="disabled"/>
 * &lt;enumeration value="obsolete"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("442aaea9-01ce-4fce-a47f-1cd651b7b10a")
@XmlType(name = "ActivationStatus")
@XmlEnum
enum ActivationStatus {
    @XmlEnumValue("enabled")
    ENABLED ("enabled"),
    @XmlEnumValue("disabled")
    DISABLED ("disabled"),
    @XmlEnumValue("obsolete")
    OBSOLETE ("obsolete");

    @objid ("fe8a88df-a1b1-4969-8a9b-950b1d947c40")
    private final String value;

    @objid ("1a04e83a-5ee3-49be-b1f4-81976cb66284")
    ActivationStatus(String v) {
        this.value = v;
    }

    @objid ("4e5a0b30-160f-4ff7-8049-d5aebd16f6ea")
    public String value() {
        return this.value;
    }

    @objid ("50953d28-b360-42aa-891e-d2995d91aad2")
    public static ActivationStatus fromValue(String v) {
        for (ActivationStatus c : ActivationStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
