/*
 * Copyright 2013 Modeliosoft
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */  
                                    

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.01.10 at 01:18:11 PM CET
//
package org.modelio.audit.preferences.persistence.old;

import javax.xml.bind.annotation.XmlRegistry;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * This object contains factory methods for each Java content .Interface and Java element .Interface generated in the
 * audit package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived .Interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 */
@objid ("a60590ed-8f01-474b-9270-88a00fa52d88")
@XmlRegistry
class ObjectFactory {
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: audit
     */
    @objid ("e3212578-3c02-4c51-af64-05191b266a1e")
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Driver }
     */
    @objid ("2c701610-67c1-4d88-9f44-37013b374161")
    public Driver createDriver() {
        return new Driver();
    }

    /**
     * Create an instance of {@link Rule }
     */
    @objid ("be2a435c-45a0-4104-9054-873012fd19ba")
    public Rule createRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link Configuration }
     */
    @objid ("34a6b609-a20b-448d-9eba-ef17456887e4")
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link RuleGroup }
     */
    @objid ("9de1f7f3-e610-44e2-81eb-889116290094")
    public RuleGroup createRuleGroup() {
        return new RuleGroup();
    }

}
