/*
 * Copyright 2013 Modeliosoft
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */  
                                    

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.01.10 at 01:18:11 PM CET
//
package org.modelio.audit.preferences.persistence.old;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{}Driver"/>
 * &lt;/sequence>
 * &lt;attribute name="ruleId" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="severity" use="required" type="{}Severity" />
 * &lt;attribute name="status" type="{}ActivationStatus" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("94ae4105-c8ed-4856-b8c3-bc89e1912276")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "driver" })
@XmlRootElement(name = "Rule")
class Rule {
    @objid ("4415099d-de12-45f1-98ee-9a1b5d708512")
    @XmlAttribute(name = "ruleId")
    protected String ruleId;

    @objid ("a920064c-0ce4-48da-afa1-76cc825832ad")
    @XmlAttribute(name = "status")
    protected ActivationStatus status;

    @objid ("6fb56f50-c885-400a-8210-c29476269aed")
    @XmlAttribute(name = "severity", required = true)
    protected Severity severity;

    @objid ("b048a047-3674-44e3-a21d-f8c7efb5951d")
    @XmlElement(name = "Driver", required = true)
    protected Driver driver;

    /**
     * Gets the value of the driver property.
     * @link Driver }
     * @return possible object is {
     */
    @objid ("26a813fb-07e2-4580-aa11-4176ff05bf26")
    public Driver getDriver() {
        return this.driver;
    }

    /**
     * Sets the value of the driver property.
     * @param value allowed object is {
     * @link Driver }
     */
    @objid ("a23d1def-3f2b-4dda-9ad5-e79bda661fba")
    public void setDriver(Driver value) {
        this.driver = value;
    }

    /**
     * Gets the value of the ruleId property.
     * @link String }
     * @return possible object is {
     */
    @objid ("bc6dc229-4390-4155-b024-269a35f476d8")
    public String getRuleId() {
        return this.ruleId;
    }

    /**
     * Sets the value of the ruleId property.
     * @param value allowed object is {
     * @link String }
     */
    @objid ("bf7c7cf0-021a-413a-8877-3a678b7f9ca8")
    public void setRuleId(String value) {
        this.ruleId = value;
    }

    /**
     * Gets the value of the severity property.
     * @link Severity }
     * @return possible object is {
     */
    @objid ("b5fd973c-6930-4604-b519-060998baa2e3")
    public Severity getSeverity() {
        return this.severity;
    }

    /**
     * Sets the value of the severity property.
     * @param value allowed object is {
     * @link Severity }
     */
    @objid ("946d4942-f635-4c9f-90e1-9b6dbcd75dea")
    public void setSeverity(Severity value) {
        this.severity = value;
    }

    /**
     * Gets the value of the status property.
     * @link ActivationStatus }
     * @return possible object is {
     */
    @objid ("64ef0040-b956-4319-b464-e98c6456ec28")
    public ActivationStatus getStatus() {
        return this.status;
    }

    /**
     * Sets the value of the status property.
     * @param value allowed object is {
     * @link ActivationStatus }
     */
    @objid ("c9d427d2-81ea-4471-be5c-d079f0553bf3")
    public void setStatus(ActivationStatus value) {
        this.status = value;
    }

}
