/*
 * Copyright 2013 Modeliosoft
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */  
                                    

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.01.10 at 01:18:11 PM CET
//
package org.modelio.audit.preferences.persistence.old;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence maxOccurs="unbounded">
 * &lt;element ref="{}Rule"/>
 * &lt;/sequence>
 * &lt;attribute name="category" type="{http://www.w3.org/2001/XMLSchema}string" default="others" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("3372d899-48b5-499b-8aec-f84ebfb6cb84")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "rule" })
@XmlRootElement(name = "RuleGroup")
class RuleGroup {
    @objid ("a1582f72-4e04-4662-bf31-b1a6fa0b993d")
    @XmlAttribute(name = "category")
    protected String category;

    @objid ("09617fe5-12f1-46b5-a725-e17fee9ec8ed")
    @XmlElement(name = "Rule", required = true)
    protected List<Rule> rule;

    /**
     * Gets the value of the rule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the rule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Rule }
     */
    @objid ("d8f3e73e-e99a-4591-9908-76cb998d8105")
    public List<Rule> getRule() {
        if (this.rule == null) {
            this.rule = new ArrayList<>();
        }
        return this.rule;
    }

    /**
     * Gets the value of the category property.
     * @link String }
     * @return possible object is {
     */
    @objid ("ff983396-962e-414a-8426-e447b72c58c8")
    public String getCategory() {
        if (this.category == null) {
            return "others";
        } else {
            return this.category;
        }
    }

    /**
     * Sets the value of the category property.
     * @param value allowed object is {
     * @link String }
     */
    @objid ("c502cfde-8167-4423-a0c7-ffd3a64e5732")
    public void setCategory(String value) {
        this.category = value;
    }

}
