/*
 * Copyright 2013 Modeliosoft
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */  
                                    

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.01.10 at 01:18:11 PM CET
//
package org.modelio.audit.preferences.persistence.old;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>
 * Java class for Severity.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="Severity">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="error"/>
 * &lt;enumeration value="warning"/>
 * &lt;enumeration value="tip"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("333ac4d9-eab5-4ec9-ab91-74ff91141e41")
@XmlType(name = "Severity")
@XmlEnum
enum Severity {
    @XmlEnumValue("error")
    ERROR ("error"),
    @XmlEnumValue("warning")
    WARNING ("warning"),
    @XmlEnumValue("tip")
    TIP ("tip");

    @objid ("2553874f-8526-40f5-97fe-a78c4ef8c3fb")
    private final String value;

    @objid ("3d758908-ccb7-4af5-9224-cc1081d18afd")
    Severity(String v) {
        this.value = v;
    }

    @objid ("5f6ace6a-465d-446d-8cea-fa26f9328293")
    public String value() {
        return this.value;
    }

    @objid ("dad3e20b-f186-4c0d-915c-fdd81b503285")
    public static Severity fromValue(String v) {
        for (Severity c : Severity.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
